// <auto-generated />
using System;
using Assignment_S02_EFCore.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assignment_S02_EFCore.Migrations.Musician_EFCore_Db
{
    [DbContext(typeof(Musician_EFCore_DbContext))]
    partial class Musician_EFCore_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Musician.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MusicianProductionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MusicianProductionId");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Musician.Album_Song", b =>
                {
                    b.Property<string>("SongTitle")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.HasKey("SongTitle", "AlbumId");

                    b.HasIndex("AlbumId");

                    b.ToTable("Album_Songs");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Musician.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Musician.Mus_Instrument", b =>
                {
                    b.Property<int>("MusicianId")
                        .HasColumnType("int");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.HasKey("MusicianId", "InstrumentId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("Mus_Instruments");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Musician.Mus_Song", b =>
                {
                    b.Property<int>("MusicianId")
                        .HasColumnType("int");

                    b.Property<string>("SongTitle")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MusicianId", "SongTitle");

                    b.HasIndex("SongTitle");

                    b.ToTable("Mus_Songs");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Musician.Musician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ph_Number")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Musicians");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Musician.Song", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Title");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Sales.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedOfficeID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedOfficeID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Sales.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Sales.Prop_Owner", b =>
                {
                    b.Property<int>("OwnId")
                        .HasColumnType("int");

                    b.Property<int>("PropId")
                        .HasColumnType("int");

                    b.Property<decimal>("percent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OwnId", "PropId");

                    b.HasIndex("PropId");

                    b.ToTable("Prop_Owner");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Sales.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListedOfficeID")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ListedOfficeID");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Sales.SalesOffice", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"));

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.HasKey("Number");

                    b.HasIndex("ManagerId")
                        .IsUnique();

                    b.ToTable("SalesOffices");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Musician.Album", b =>
                {
                    b.HasOne("Assignment_S02_EFCore.Models.Musician.Musician", "MusicianProduction")
                        .WithMany("AlbumsProduction")
                        .HasForeignKey("MusicianProductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MusicianProduction");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Musician.Album_Song", b =>
                {
                    b.HasOne("Assignment_S02_EFCore.Models.Musician.Album", "Album")
                        .WithMany("ContainSongs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment_S02_EFCore.Models.Musician.Song", "Song")
                        .WithMany("SongsInAlbum")
                        .HasForeignKey("SongTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Musician.Mus_Instrument", b =>
                {
                    b.HasOne("Assignment_S02_EFCore.Models.Musician.Instrument", "Instrument")
                        .WithMany("InstrumentPlayed")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment_S02_EFCore.Models.Musician.Musician", "Musician")
                        .WithMany("PlayedInstrument")
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Musician");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Musician.Mus_Song", b =>
                {
                    b.HasOne("Assignment_S02_EFCore.Models.Musician.Musician", "Musician")
                        .WithMany("PerformedSongs")
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment_S02_EFCore.Models.Musician.Song", "Song")
                        .WithMany("SongsPerformed")
                        .HasForeignKey("SongTitle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musician");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Sales.Employee", b =>
                {
                    b.HasOne("Assignment_S02_EFCore.Models.Sales.SalesOffice", "AssignedOffice")
                        .WithMany("AssignedEmployee")
                        .HasForeignKey("AssignedOfficeID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AssignedOffice");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Sales.Prop_Owner", b =>
                {
                    b.HasOne("Assignment_S02_EFCore.Models.Sales.Owner", "Owner")
                        .WithMany("OwnedProperties")
                        .HasForeignKey("OwnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment_S02_EFCore.Models.Sales.Property", "Property")
                        .WithMany("PropertiesOwned")
                        .HasForeignKey("PropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Sales.Property", b =>
                {
                    b.HasOne("Assignment_S02_EFCore.Models.Sales.SalesOffice", "ListedOffice")
                        .WithMany("ListsOfProperties")
                        .HasForeignKey("ListedOfficeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListedOffice");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Sales.SalesOffice", b =>
                {
                    b.HasOne("Assignment_S02_EFCore.Models.Sales.Employee", "Manger")
                        .WithOne("ManagedOffice")
                        .HasForeignKey("Assignment_S02_EFCore.Models.Sales.SalesOffice", "ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manger");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Musician.Album", b =>
                {
                    b.Navigation("ContainSongs");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Musician.Instrument", b =>
                {
                    b.Navigation("InstrumentPlayed");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Musician.Musician", b =>
                {
                    b.Navigation("AlbumsProduction");

                    b.Navigation("PerformedSongs");

                    b.Navigation("PlayedInstrument");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Musician.Song", b =>
                {
                    b.Navigation("SongsInAlbum");

                    b.Navigation("SongsPerformed");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Sales.Employee", b =>
                {
                    b.Navigation("ManagedOffice");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Sales.Owner", b =>
                {
                    b.Navigation("OwnedProperties");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Sales.Property", b =>
                {
                    b.Navigation("PropertiesOwned");
                });

            modelBuilder.Entity("Assignment_S02_EFCore.Models.Sales.SalesOffice", b =>
                {
                    b.Navigation("AssignedEmployee");

                    b.Navigation("ListsOfProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
